-- Templates de email transacionais para eventos de pagamento

INSERT INTO public.templates_email (nome, assunto, html_content, variaveis, is_active) VALUES
(
  'Pagamento aprovado',
  'Pagamento confirmado — SimulaCotas Pro',
  '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body style="margin:0;padding:0;background-color:#f5f5f7;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica,Arial,sans-serif"><table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f5f5f7;padding:40px 20px"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.06)"><tr><td style="background:linear-gradient(135deg,#0D1B4B,#152260);padding:32px 40px;text-align:center"><img src="https://simulacotas.vercel.app/assets/logo.png" alt="SimulaCotas" height="40" style="height:40px"></td></tr><tr><td style="padding:40px"><div style="background-color:#dcfce7;border-radius:12px;padding:16px 20px;margin-bottom:24px;text-align:center"><p style="margin:0;font-size:14px;font-weight:600;color:#166534">Pagamento confirmado</p></div><h1 style="margin:0 0 8px;font-size:24px;font-weight:700;color:#1e293b">Obrigado, {{nome}}!</h1><p style="margin:0 0 24px;font-size:16px;color:#64748b;line-height:1.6">Seu pagamento de <strong style="color:#0D1B4B">R$ {{valor}}</strong> via {{metodo}} foi confirmado em {{data}}.</p><table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f8fafc;border-radius:12px;margin-bottom:24px"><tr><td style="padding:20px"><p style="margin:0 0 4px;font-size:12px;color:#94a3b8;text-transform:uppercase;letter-spacing:1px">Seu plano</p><p style="margin:0;font-size:20px;font-weight:800;color:#0D1B4B">SimulaCotas Pro</p><p style="margin:8px 0 0;font-size:13px;color:#64748b">Simulações ilimitadas · PDF com branding · WhatsApp</p></td></tr></table><table cellpadding="0" cellspacing="0" style="margin:0 auto"><tr><td style="background-color:#0D1B4B;border-radius:12px;padding:14px 32px"><a href="https://simulacotas.com.br/app" style="color:#CCEE00;text-decoration:none;font-size:16px;font-weight:700">Acessar SimulaCotas</a></td></tr></table></td></tr><tr><td style="padding:24px 40px;background-color:#f8fafc;border-top:1px solid #f1f5f9;text-align:center"><p style="margin:0;font-size:12px;color:#94a3b8">SimulaCotas — Simulações de consórcio profissionais</p></td></tr></table></td></tr></table></body></html>',
  '["nome","valor","metodo","data"]',
  true
),
(
  'Pagamento falhou',
  'Não conseguimos processar seu pagamento',
  '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body style="margin:0;padding:0;background-color:#f5f5f7;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica,Arial,sans-serif"><table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f5f5f7;padding:40px 20px"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.06)"><tr><td style="background:linear-gradient(135deg,#0D1B4B,#152260);padding:32px 40px;text-align:center"><img src="https://simulacotas.vercel.app/assets/logo.png" alt="SimulaCotas" height="40" style="height:40px"></td></tr><tr><td style="padding:40px"><div style="background-color:#fef2f2;border-radius:12px;padding:16px 20px;margin-bottom:24px;text-align:center"><p style="margin:0;font-size:14px;font-weight:600;color:#991b1b">Pagamento não processado</p></div><h1 style="margin:0 0 8px;font-size:24px;font-weight:700;color:#1e293b">{{nome}}, houve um problema</h1><p style="margin:0 0 24px;font-size:16px;color:#64748b;line-height:1.6">Não conseguimos processar o pagamento de <strong style="color:#0D1B4B">R$ {{valor}}</strong> da sua assinatura SimulaCotas Pro. Esta foi a tentativa {{tentativas}} de 3.</p><p style="margin:0 0 24px;font-size:14px;color:#ef4444;line-height:1.5">Após 3 tentativas falhadas, seu acesso será suspenso automaticamente.</p><table cellpadding="0" cellspacing="0" style="margin:0 auto"><tr><td style="background-color:#0D1B4B;border-radius:12px;padding:14px 32px"><a href="https://simulacotas.com.br/app/checkout" style="color:#CCEE00;text-decoration:none;font-size:16px;font-weight:700">Atualizar forma de pagamento</a></td></tr></table></td></tr><tr><td style="padding:24px 40px;background-color:#f8fafc;border-top:1px solid #f1f5f9;text-align:center"><p style="margin:0;font-size:12px;color:#94a3b8">SimulaCotas — Simulações de consórcio profissionais</p></td></tr></table></td></tr></table></body></html>',
  '["nome","valor","tentativas"]',
  true
),
(
  'Assinatura cancelada',
  'Sua assinatura foi cancelada — SimulaCotas',
  '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body style="margin:0;padding:0;background-color:#f5f5f7;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica,Arial,sans-serif"><table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f5f5f7;padding:40px 20px"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.06)"><tr><td style="background:linear-gradient(135deg,#0D1B4B,#152260);padding:32px 40px;text-align:center"><img src="https://simulacotas.vercel.app/assets/logo.png" alt="SimulaCotas" height="40" style="height:40px"></td></tr><tr><td style="padding:40px"><h1 style="margin:0 0 8px;font-size:24px;font-weight:700;color:#1e293b">{{nome}}, sentimos muito</h1><p style="margin:0 0 24px;font-size:16px;color:#64748b;line-height:1.6">Sua assinatura do SimulaCotas Pro foi cancelada. Seus dados e simulações continuam salvos caso queira voltar.</p><table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f8fafc;border-radius:12px;margin-bottom:24px"><tr><td style="padding:20px"><p style="margin:0 0 8px;font-size:14px;font-weight:600;color:#1e293b">O que você perde:</p><p style="margin:0;font-size:13px;color:#64748b;line-height:1.8">• Simulações ilimitadas<br>• PDF com seu branding<br>• Envio por WhatsApp em 1 toque<br>• Histórico e cadastro de clientes</p></td></tr></table><table cellpadding="0" cellspacing="0" style="margin:0 auto"><tr><td style="background-color:#CCEE00;border-radius:12px;padding:14px 32px"><a href="https://simulacotas.com.br/app/checkout" style="color:#0D1B4B;text-decoration:none;font-size:16px;font-weight:700">Reativar minha assinatura</a></td></tr></table><p style="margin:24px 0 0;font-size:13px;color:#94a3b8;text-align:center">Seus dados ficam preservados por 90 dias.</p></td></tr><tr><td style="padding:24px 40px;background-color:#f8fafc;border-top:1px solid #f1f5f9;text-align:center"><p style="margin:0;font-size:12px;color:#94a3b8">SimulaCotas — Simulações de consórcio profissionais</p></td></tr></table></td></tr></table></body></html>',
  '["nome"]',
  true
)
ON CONFLICT DO NOTHING;
