-- Atualizar templates de email com layout profissional branded

-- Template: Boas-vindas
UPDATE public.templates_email
SET assunto = 'Bem-vindo ao SimulaCotas! Seu trial de 3 dias começou',
    html_content = '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Bem-vindo ao SimulaCotas</title></head><body style="margin:0;padding:0;background-color:#f5f5f7;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica,Arial,sans-serif"><table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f5f5f7;padding:40px 20px"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.06)"><tr><td style="background:linear-gradient(135deg,#0D1B4B,#152260);padding:32px 40px;text-align:center"><img src="https://simulacotas.vercel.app/assets/logo.png" alt="SimulaCotas" height="40" style="height:40px"></td></tr><tr><td style="padding:40px"><h1 style="margin:0 0 8px;font-size:24px;font-weight:700;color:#1e293b">Olá, {{nome}}!</h1><p style="margin:0 0 24px;font-size:16px;color:#64748b;line-height:1.6">Seu trial gratuito de 3 dias começou. Agora você pode criar propostas de consórcio profissionais em 30 segundos.</p><table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f8fafc;border-radius:12px;margin-bottom:24px"><tr><td style="padding:20px"><table width="100%" cellpadding="0" cellspacing="0"><tr><td width="33%" style="text-align:center;padding:8px"><p style="margin:0;font-size:24px;font-weight:800;color:#0D1B4B">6+</p><p style="margin:4px 0 0;font-size:12px;color:#94a3b8">Administradoras</p></td><td width="33%" style="text-align:center;padding:8px"><p style="margin:0;font-size:24px;font-weight:800;color:#0D1B4B">3</p><p style="margin:4px 0 0;font-size:12px;color:#94a3b8">Modalidades</p></td><td width="33%" style="text-align:center;padding:8px"><p style="margin:0;font-size:24px;font-weight:800;color:#0D1B4B">30s</p><p style="margin:4px 0 0;font-size:12px;color:#94a3b8">Por simulação</p></td></tr></table></td></tr></table><table cellpadding="0" cellspacing="0" style="margin:0 auto"><tr><td style="background-color:#0D1B4B;border-radius:12px;padding:14px 32px"><a href="{{link_app}}" style="color:#CCEE00;text-decoration:none;font-size:16px;font-weight:700">Acessar SimulaCotas</a></td></tr></table><p style="margin:24px 0 0;font-size:14px;color:#94a3b8;line-height:1.5">Dica: comece selecionando uma administradora e preencha os dados do cliente. Em segundos terá uma proposta profissional pronta para enviar!</p></td></tr><tr><td style="padding:24px 40px;background-color:#f8fafc;border-top:1px solid #f1f5f9;text-align:center"><p style="margin:0;font-size:12px;color:#94a3b8">SimulaCotas — Simulações de consórcio profissionais</p><p style="margin:4px 0 0;font-size:11px;color:#cbd5e1">Você recebeu este email porque criou uma conta no SimulaCotas.</p></td></tr></table></td></tr></table></body></html>'
WHERE nome = 'Boas-vindas';

-- Template: Trial expirando
UPDATE public.templates_email
SET assunto = '{{nome}}, seu trial acaba amanhã!',
    html_content = '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Trial expirando</title></head><body style="margin:0;padding:0;background-color:#f5f5f7;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica,Arial,sans-serif"><table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f5f5f7;padding:40px 20px"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.06)"><tr><td style="background:linear-gradient(135deg,#0D1B4B,#152260);padding:32px 40px;text-align:center"><img src="https://simulacotas.vercel.app/assets/logo.png" alt="SimulaCotas" height="40" style="height:40px"></td></tr><tr><td style="padding:40px"><div style="background-color:#fef3c7;border-radius:12px;padding:16px 20px;margin-bottom:24px;text-align:center"><p style="margin:0;font-size:14px;font-weight:600;color:#92400e">Seu trial expira amanhã</p></div><h1 style="margin:0 0 8px;font-size:24px;font-weight:700;color:#1e293b">{{nome}}, não perca seu progresso!</h1><p style="margin:0 0 24px;font-size:16px;color:#64748b;line-height:1.6">Você já gerou <strong style="color:#0D1B4B">{{propostas_count}} propostas</strong> durante o trial. Assine o plano Pro para continuar gerando simulações ilimitadas.</p><table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f8fafc;border-radius:12px;margin-bottom:24px"><tr><td style="padding:20px"><p style="margin:0 0 4px;font-size:12px;color:#94a3b8;text-transform:uppercase;letter-spacing:1px">Plano Pro</p><p style="margin:0;font-size:32px;font-weight:800;color:#0D1B4B">R$ 189,90<span style="font-size:14px;font-weight:400;color:#94a3b8">/mês</span></p><p style="margin:8px 0 0;font-size:13px;color:#64748b">Simulações ilimitadas · PDF com branding · WhatsApp em 1 toque</p></td></tr></table><table cellpadding="0" cellspacing="0" style="margin:0 auto"><tr><td style="background-color:#0D1B4B;border-radius:12px;padding:14px 32px"><a href="{{link_upgrade}}" style="color:#CCEE00;text-decoration:none;font-size:16px;font-weight:700">Assinar agora</a></td></tr></table></td></tr><tr><td style="padding:24px 40px;background-color:#f8fafc;border-top:1px solid #f1f5f9;text-align:center"><p style="margin:0;font-size:12px;color:#94a3b8">SimulaCotas — Simulações de consórcio profissionais</p><p style="margin:4px 0 0;font-size:11px;color:#cbd5e1">Você recebeu este email porque tem uma conta no SimulaCotas.</p></td></tr></table></td></tr></table></body></html>'
WHERE nome = 'Trial expirando';

-- Template: Reativação com cupom
UPDATE public.templates_email
SET assunto = '{{nome}}, volte com desconto exclusivo!',
    html_content = '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Volte para o SimulaCotas</title></head><body style="margin:0;padding:0;background-color:#f5f5f7;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica,Arial,sans-serif"><table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f5f5f7;padding:40px 20px"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.06)"><tr><td style="background:linear-gradient(135deg,#0D1B4B,#152260);padding:32px 40px;text-align:center"><img src="https://simulacotas.vercel.app/assets/logo.png" alt="SimulaCotas" height="40" style="height:40px"></td></tr><tr><td style="padding:40px"><h1 style="margin:0 0 8px;font-size:24px;font-weight:700;color:#1e293b">Sentimos sua falta, {{nome}}!</h1><p style="margin:0 0 24px;font-size:16px;color:#64748b;line-height:1.6">Seu trial expirou, mas preparamos uma oferta especial para você voltar.</p><table width="100%" cellpadding="0" cellspacing="0" style="background:linear-gradient(135deg,#0D1B4B,#152260);border-radius:16px;margin-bottom:24px"><tr><td style="padding:28px;text-align:center"><p style="margin:0 0 4px;font-size:12px;color:#94a3b8;text-transform:uppercase;letter-spacing:2px">Cupom exclusivo</p><p style="margin:0;font-size:36px;font-weight:800;color:#CCEE00;letter-spacing:4px">{{cupom}}</p><p style="margin:8px 0 0;font-size:16px;color:#ffffff">{{desconto}}% de desconto no primeiro mês</p></td></tr></table><table cellpadding="0" cellspacing="0" style="margin:0 auto"><tr><td style="background-color:#CCEE00;border-radius:12px;padding:14px 32px"><a href="{{link_reativacao}}" style="color:#0D1B4B;text-decoration:none;font-size:16px;font-weight:700">Reativar minha conta</a></td></tr></table><p style="margin:24px 0 0;font-size:13px;color:#94a3b8;line-height:1.5;text-align:center">Oferta válida por tempo limitado. Seus dados e simulações anteriores estão preservados.</p></td></tr><tr><td style="padding:24px 40px;background-color:#f8fafc;border-top:1px solid #f1f5f9;text-align:center"><p style="margin:0;font-size:12px;color:#94a3b8">SimulaCotas — Simulações de consórcio profissionais</p><p style="margin:4px 0 0;font-size:11px;color:#cbd5e1">Você recebeu este email porque tem uma conta no SimulaCotas.</p></td></tr></table></td></tr></table></body></html>'
WHERE nome = 'Reativação com cupom';

-- Novo template: Reset de senha (para uso futuro via SMTP customizado)
INSERT INTO public.templates_email (nome, assunto, html_content, variaveis, is_active) VALUES
(
  'Reset de senha',
  'Redefinir sua senha — SimulaCotas',
  '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Reset de senha</title></head><body style="margin:0;padding:0;background-color:#f5f5f7;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica,Arial,sans-serif"><table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f5f5f7;padding:40px 20px"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.06)"><tr><td style="background:linear-gradient(135deg,#0D1B4B,#152260);padding:32px 40px;text-align:center"><img src="https://simulacotas.vercel.app/assets/logo.png" alt="SimulaCotas" height="40" style="height:40px"></td></tr><tr><td style="padding:40px"><h1 style="margin:0 0 8px;font-size:24px;font-weight:700;color:#1e293b">Redefinir sua senha</h1><p style="margin:0 0 24px;font-size:16px;color:#64748b;line-height:1.6">Recebemos uma solicitação para redefinir a senha da sua conta SimulaCotas. Clique no botão abaixo para criar uma nova senha.</p><table cellpadding="0" cellspacing="0" style="margin:0 auto"><tr><td style="background-color:#0D1B4B;border-radius:12px;padding:14px 32px"><a href="{{link_reset}}" style="color:#CCEE00;text-decoration:none;font-size:16px;font-weight:700">Redefinir senha</a></td></tr></table><p style="margin:24px 0 0;font-size:13px;color:#94a3b8;line-height:1.5">Se você não solicitou esta alteração, ignore este email. O link expira em 1 hora.</p></td></tr><tr><td style="padding:24px 40px;background-color:#f8fafc;border-top:1px solid #f1f5f9;text-align:center"><p style="margin:0;font-size:12px;color:#94a3b8">SimulaCotas — Simulações de consórcio profissionais</p><p style="margin:4px 0 0;font-size:11px;color:#cbd5e1">Você recebeu este email porque solicitou a redefinição de senha.</p></td></tr></table></td></tr></table></body></html>',
  '["nome","link_reset"]',
  true
),
(
  'Confirmação de conta',
  'Confirme seu email — SimulaCotas',
  '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Confirme seu email</title></head><body style="margin:0;padding:0;background-color:#f5f5f7;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica,Arial,sans-serif"><table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f5f5f7;padding:40px 20px"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.06)"><tr><td style="background:linear-gradient(135deg,#0D1B4B,#152260);padding:32px 40px;text-align:center"><img src="https://simulacotas.vercel.app/assets/logo.png" alt="SimulaCotas" height="40" style="height:40px"></td></tr><tr><td style="padding:40px"><h1 style="margin:0 0 8px;font-size:24px;font-weight:700;color:#1e293b">Confirme seu email</h1><p style="margin:0 0 24px;font-size:16px;color:#64748b;line-height:1.6">Olá, {{nome}}! Clique no botão abaixo para confirmar seu email e ativar sua conta SimulaCotas.</p><table cellpadding="0" cellspacing="0" style="margin:0 auto"><tr><td style="background-color:#CCEE00;border-radius:12px;padding:14px 32px"><a href="{{link_confirmacao}}" style="color:#0D1B4B;text-decoration:none;font-size:16px;font-weight:700">Confirmar email</a></td></tr></table><p style="margin:24px 0 0;font-size:13px;color:#94a3b8;line-height:1.5">Se você não criou esta conta, ignore este email.</p></td></tr><tr><td style="padding:24px 40px;background-color:#f8fafc;border-top:1px solid #f1f5f9;text-align:center"><p style="margin:0;font-size:12px;color:#94a3b8">SimulaCotas — Simulações de consórcio profissionais</p></td></tr></table></td></tr></table></body></html>',
  '["nome","link_confirmacao"]',
  true
);
